name: praca_inz
description: Code for my BSc
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #SDK
  flutter:
    sdk: flutter

  #Architecture
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0

  #Localizations
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  #Assets
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0

  #Network
  cached_network_image: ^3.1.0

  #Serialization
  json_annotation: ^4.1.0

  #Utility
  equatable: ^2.0.3

dependency_overrides:
  analyzer: 2.2.0 #Required by flutter_gen_runner

dev_dependencies:
  #Code generation & build running
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.2
  json_serializable: ^5.0.2

  #Static Analysis
  flutter_lints: ^1.0.4

  #Native splash
  flutter_native_splash: ^1.2.3

  #Tests
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #Disabled because of flutter_gen
  generate: false
  assets:
    - assets/images/

#TODO create image for splash screen
flutter_native_splash:
  image: assets/images/splash_screen.jpg
  color: "FFFFFF"

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
