name: praca_inz
description: Code for my BSc

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  injectable: ^1.5.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_native_splash: ^1.2.3
  freezed: ^0.14.5
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Padauk
      fonts:
        - asset: fonts/Padauk-Regular.ttf
        - asset: fonts/Padauk-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Trirong
      fonts:
        - asset: fonts/Trirong-Thin.ttf
        - asset: fonts/Trirong-Light.ttf
          weight: 700

#TODO create image for splash screen
flutter_native_splash: 
  image: assets/images/splash_screen.jpg
  color: "FFFFFF"