name: praca_inz
description: Code for my BSc
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  #SDK
  flutter:
    sdk: flutter

  #Architecture
  flutter_bloc: 8.0.0
  get_it: 7.2.0

  #Localizations
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  #Assets
  google_fonts: 2.1.0
  flutter_svg: 0.23.0+1

  # Data & Persistence
  shared_preferences: 2.0.11

  #Network
  cached_network_image: 3.1.0

  #Serialization
  json_annotation: 4.3.0

  #Utility
  collection: 1.15.0
  equatable: 2.0.3
  dartz: 0.10.0
  email_validator: 2.0.1
  moving_average: 0.3.0

  #Sensors
  sensors_plus: 1.2.1

  #Integrations
  cloud_firestore: 2.5.3
  firebase_auth: 3.1.3
  firebase_analytics: 8.3.2
  firebase_core: 1.7.0
  firebase_crashlytics: 2.2.3
  firebase_performance: 0.7.1+1

dependency_overrides:
  analyzer: 2.6.0 #Required by flutter_gen_runner

dev_dependencies:
  #Code generation & build running
  build_runner: 2.1.4
  flutter_gen_runner: 4.0.0
  json_serializable: 6.0.0

  #Static Analysis
  flutter_lints: 1.0.4

  #Native splash
  flutter_native_splash: 1.2.4

  #Tests
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #Disabled because of flutter_gen
  generate: false
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/splash_screen.png
  color: "#ffffff"

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
